# Generated by Django 5.2.6 on 2025-09-18 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'пост', 'verbose_name_plural': 'посты'},
        ),
    ]
