# Generated by Django 5.2.6 on 2025-09-19 10:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'обратная связь', 'verbose_name_plural': 'обратные связи'},
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('suggestion', 'Предложение'), ('problem', 'Проблема'), ('improvement', 'Идея улучшения'), ('other', 'Другое')], default='suggestion', max_length=20, verbose_name='Тип обратной связи'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=10, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда обработано'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Кем обработано'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='response',
            field=models.TextField(blank=True, verbose_name='Ответ на обратную связь'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='title',
            field=models.CharField(default='Без заголовка', max_length=200, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
