# Generated by Django 5.2.6 on 2025-09-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_feedback_options_feedback_feedback_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='title',
            field=models.CharField(default='Без заголовка', max_length=200, verbose_name='Заголовок'),
        ),
    ]
